# Generated by Django 6.0.6 on 2026-09-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_basket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='Baskets',
        ),
    ]
