# Generated by Django 6.0.6 on 2026-09-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_power_compare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='category',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='height',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='image',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='length',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='life',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='power',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='price',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='user',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='width',
        ),
        migrations.AddField(
            model_name='compare',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
