# Generated by Django 6.0.6 on 2026-09-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_compare_category_remove_compare_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='name',
        ),
    ]
