# Generated by Django 6.0.6 on 2026-10-09 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_reviewsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
